# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:29
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('c_type', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], verbose_name='分类级别')),
                ('is_show_navi', models.BooleanField(default=False, verbose_name='是否显示再导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Classification', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类-plu',
            },
        ),
        migrations.CreateModel(
            name='ClassImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='图片名称')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Classification', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '分类图片',
                'verbose_name_plural': '分类图片-plu',
            },
        ),
        migrations.CreateModel(
            name='IndexShuffingFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='图片名称')),
                ('img', models.ImageField(upload_to='', verbose_name='商品图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='图片位置')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_cover_img', models.ImageField(upload_to='', verbose_name='商品封面图')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=100, verbose_name='商品描述')),
                ('prise', models.FloatField(verbose_name='价格')),
                ('particulars', DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情')),
                ('activity_prise', models.FloatField(blank=True, null=True, verbose_name='活动价格')),
                ('lower_time', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('inventory_num', models.IntegerField(default=0, verbose_name='库存')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('sales_numm', models.IntegerField(default=0, verbose_name='销售量')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否为新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否为热卖')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上架时间')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Classification', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ShuffingFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='图片名称')),
                ('img', models.ImageField(upload_to='', verbose_name='商品图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='图片位置')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Merchandise', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
        migrations.AddField(
            model_name='indexshuffingfigure',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Merchandise', verbose_name='商品'),
        ),
    ]
