# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171203_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='code',
            field=models.CharField(max_length=30, verbose_name='唯一编码'),
        ),
    ]
