# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20171204_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='prise',
            new_name='market_prise',
        ),
    ]
