# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20171204_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='market_prise',
            new_name='market_price',
        ),
        migrations.RenameField(
            model_name='merchandise',
            old_name='sale_prise',
            new_name='sale_price',
        ),
    ]
