# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20171204_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='商品描述'),
        ),
    ]
