# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已取消'), (10, '异常')], verbose_name='订单状态')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='留言')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('pay_type', models.SmallIntegerField(choices=[(0, '支付宝'), (1, '微信')], verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pay_sn', models.CharField(max_length=50, verbose_name='支付编号')),
                ('receive_person', models.CharField(max_length=20, verbose_name='收货人')),
                ('receive_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('receive_mobile', models.CharField(max_length=10, verbose_name='收货电话')),
                ('logistics_status', models.SmallIntegerField(choices=[(0, '未发货'), (1, '运输中'), (2, '已签收'), (3, '异常')], verbose_name='物流状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMerc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCardMerc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0, verbose_name='金额')),
                ('total_num', models.ImageField(default=0, upload_to='', verbose_name='总数量')),
            ],
        ),
    ]
