# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0008_auto_20171204_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已取消'), (10, '异常')], default=0, verbose_name='订单状态')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='留言')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('pay_type', models.SmallIntegerField(choices=[(0, '支付宝'), (1, '微信')], verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pay_sn', models.CharField(blank=True, max_length=64, verbose_name='支付编号')),
                ('receive_person', models.CharField(max_length=20, verbose_name='收货人')),
                ('receive_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('receive_mobile', models.CharField(max_length=20, verbose_name='收货电话')),
                ('logistics_status', models.SmallIntegerField(choices=[(0, '未发货'), (1, '运输中'), (2, '已签收'), (3, '异常')], default=0, verbose_name='物流状态')),
                ('total_amount', models.FloatField(default=0, verbose_name='总价')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMerc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.FloatField(verbose_name='单价')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Merchandise', verbose_name='商品ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transact.Order', verbose_name='所属订单')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCardMerc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Merchandise', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
