# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_test', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='c_test.Company'),
            preserve_default=False,
        ),
    ]
