# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_test', '0003_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='c_test.Company'),
        ),
    ]
